FROM debian:12
RUN apt update && apt install -y \
    python3-matplotlib python3-numpy python3-pip python3-pwntools ipython3 libxtst-dev libxext-dev \
    libxrender-dev libfreetype6-dev libfontconfig1 libgtk2.0-0 libx11-xcb1 \
    libxslt1.1 libxxf86vm1 x11-apps